version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600 # Set the timeout for this script (in seconds)
      runas: root  # Specify the user as whom the script should run (root in this case)
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 600
      runas: root

